mode : "exact"
theme : "advanced"
language : "<%= I18n.locale.to_s.split('-')[0].downcase %>"
skin : "o2k7"
skin_variant : "silver"
width : "98%"
plugins : "safari,style,layer,table,advhr,advimage,inlinepopups,insertdatetime,preview,media,searchreplace,contextmenu,paste,directionality,fullscreen,noneditable,visualchars,nonbreaking,xhtmlxtras,template"

# Theme options
theme_advanced_buttons1 : "cut,copy,paste,pastetext,pasteword,|,search,|,undo,redo,|,link,unlink,anchor,image,cleanup,help,code,|,preview,|,fullscreen"
theme_advanced_buttons2 : "bold,italic,underline,strikethrough,|,justifyleft,justifycenter,justifyright,justifyfull,|,sub,sup,|,bullist,numlist,|,outdent,indent,|,insertdate,inserttime,|,charmap,visualchars"
theme_advanced_buttons3 : "styleselect,formatselect,fontselect,fontsizeselect,|,forecolor,backcolor"
theme_advanced_buttons4 : "tablecontrols,|,hr,removeformat,visualaid,|,blockquote"
theme_advanced_toolbar_location : "top"
theme_advanced_toolbar_align : "left"
theme_advanced_statusbar_location : "bottom"
theme_advanced_resizing : false


